---
- name: Include OS family specific vars
  with_first_found:
    - "../vars/os-families/{{ ansible_os_family }}.yml"
  ansible.builtin.include_vars: "{{ item }}"

- name: Add Microsoft Edge repository
  ansible.builtin.include_tasks: "add-repo-{{ ansible_os_family }}.yml"

- name: Ensure Microsoft Edge present
  ansible.builtin.package:
    name: "{{ edge_package }}"
    state: present
  become: true
